Completed Task6
yshurhay/UP pull request #6
Opened 2020-05-18 08:27 UTC by yshurhay

2020-05-18 15:13 UTC, smiakchilo commented
This is a frontend task. You should have asked for a review from a frontent mentor
BTW: Commit messages are virtually missing. A commit message **must** contain comprehensive info on what exactly has been done in this or that commit. Students have been warned on that multiple times

2020-05-19 11:38 UTC, MaksimViarenich requested changes

2020-05-19 11:38 UTC, MaksimViarenich commented on task6/posts.js
> +                return false;
Привет Паланевичу

2020-05-24 13:33 UTC, MaksimViarenich reviewed
Задание будет принято, если оно будет выполнено Вами

2020-05-28 08:28 UTC, MaksimViarenich approved these changes
Все еще вижу отсылки к Паланевичу, но защитаю

2020-05-28 08:28 UTC, MaksimViarenich commented on UI/style.css
> +body {
Code style

2020-05-28 08:28 UTC, MaksimViarenich commented on task4/OpenTriviaAPI/Open Trivia API.postman_collection.json
> +{
In this PR I shouldn't see BE code, it's UI task only

2020-05-28 08:28 UTC, MaksimViarenich commented on task6/posts.js
> +            }
`switch...case`

2020-05-28 10:13 UTC, merged